apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zvlseiv7k-nodejs 
  janus-idp.io/tekton: zvlseiv7k-nodejs
  backstage.io/kubernetes-id: zvlseiv7k-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zvlseiv7k-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml